name: gallery
description: Gallery project to showcase foxsys_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  foxsys_ui:
    path: ../
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
